kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service-autoscaling
spec:
  type: NodePort
  selector:
    app: train-schedule-autoscaling
  ports:
  - protocol: TCP
    port: 6000
    nodePort: 6000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment-autoscaling
  labels:
    app: train-schedule-autoscaling
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule-autoscaling
  template:
    metadata:
      labels:
        app: train-schedule-autoscaling
    spec:
      containers:
      - name: train-schedule-autoscaling
        image: jduarte104/train-schedule:latest
        ports:
        - containerPort: 6000
        livenessProbe:
          httpGet:
            path: /
            port: 6000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
